### PR TITLE
Fix length of function after validating it #1131

### LINKED ISSUE #1131: Creating a toplevel function breakes the code
### Steps to Reproduce

1. New project
2. Navigate to top level
3. tab -> `def foo` 
4. get inside
5. tab -> 15
6. go to top level

### Expected Result

You should see two nodes, `main` and `foo`

### Actual Result

There are 2 nodes `foo` and `e <<`

### Luna Version
1.4.101.6

### PR DESCRIPTION
**Pull request by mikusp**
### Pull Request Description

Fixes #1131 and #1132 

### Checklist
Please include the following checklist in your PR:

- [  ] The documentation has been updated if necessary.
- [  ] The code conforms to the [Luna Style Guide](https://github.com/luna/wiki/blob/master/code-style/01.general.md) if it is Haskell.
- [  ] The code has been tested where possible.

### CODE REVIEW

File: libs/luna-empire/src/Empire/ASTOps/Builder.hs [hunk 1]
```diff
@@ -360,6 +360,7 @@ ensureFunctionIsValid = do
                 matchExpr self $ \case
                     ASGFunction _ _ b -> putLayer @SpanOffset b $
                         fromIntegral $ length (":\n    " :: String)
+                Code.gossipLengthsChangedBy (fromIntegral $ Text.length section) =<< target b
```
Comment (piotrMocz) [inline libs/luna-empire/src/Empire/ASTOps/Builder.hs]: What's this type here? If that's an `Integer`, I would be inclined to change it into a simple `Int`, for both performance and code readability.

Comment (mikusp) [reply libs/luna-empire/src/Empire/ASTOps/Builder.hs]: It's Delta, newtype for Word64
