### PR TITLE
Fix reading imports from a file #1101

### LINKED ISSUE #1101: Importing modules below initial Std.Base will result in non exhaustive pattern match error
### General Summary

This bug basically messes up with the parser and the visualization part in general, as soon as this bug happens, you will have to start a new project in order to work on the code, even deleting the whole file content won't help.

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Create a new project.
2. import a module **BELOW** `import Std.Base` 
3. Observe

### Expected Result

This error shouldn't raise at all!

### Actual Result
image

In this picture I tried to delete the file content and start over after reproducing the bag

### Luna Version
Luna studio v1.4.101.6

### PR DESCRIPTION
**Pull request by mikusp**
### Pull Request Description

Fixes #1101, as now it is a possibility that Invalid node is present in imports.

### Checklist
Please include the following checklist in your PR:

- [  ] The documentation has been updated if necessary.
- [  ] The code conforms to the [Luna Style Guide](https://github.com/luna/wiki/blob/master/code-style/01.general.md) if it is Haskell.
- [  ] The code has been tested where possible.

### CODE REVIEW

File: libs/luna-empire/src/Empire/Commands/Graph.hs [hunk 1]
```diff
@@ -1703,7 +1703,10 @@ getImportsInFile = do
                                     ImportSrc n -> case n of
                                         Term.Absolute n -> do
                                             let n' = convert n
-                                            return $ convert $ nameToString n'
+                                            return $ Just $ convert $ nameToString n'
+                                    _ -> return Nothing
+                            _ -> return Nothing
+    return $ catMaybes imports
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph.hs]: This code is ugly and should be refactored. It actually is refactored in another PR.

Consider this:
```
getImportsInFile :: ClassOp [Text]
getImportsInFile = matchUnit =<< use Graph.clsClass where
    matchUnit unit = matchExpr unit $ \(Unit imps _ _) -> 
        matchImports =<< source imps
    matchImports imps = matchExpr imps $ \(ImportHub imps') -> 
        mapM matchImport =<< mapM source =<< ptrListToList imps'
    matchImport imp = matchExpr imp $ \case
        Import absolute _ -> matchAbsolute =<< source absolute
        _                 -> pure Nothing
    matchAbsolute a = matchExpr a $ \case
        ImportSrc (Term.Absolute n) -> pure . Just . nameToText $ convert n
        _                           -> pure . Nothing

```

Comment (mikusp) [reply libs/luna-empire/src/Empire/Commands/Graph.hs]: Merge the other PR and I'll resolve the conflict

Comment (ljkania) [reply libs/luna-empire/src/Empire/Commands/Graph.hs]: for my own sake I need to write this down, you could do: `fmap catMaybes . matchUnit =<< use Graph.clsClass where`
