### PR TITLE
Fix real sliders (hopefully the last time)

### LINKED ISSUE #994: Sliders are broken with new core
Error is:
```
Char.digitToInt: not a digit '.'
CallStack (from -prof):
while processing event
empire.graph.node.defaultValue.response
```

### PR DESCRIPTION
**Pull request by mikusp**
Fixes #994. Real sliders are now one of the most thoroughly tested features.

### CODE REVIEW

File: libs/luna-empire/src/Empire/ASTOps/Parse.hs [hunk 1]
```diff
@@ -202,12 +203,24 @@ parsePortDefault (Constant (TextValue s)) = do
...
+        sc          = Scientific.fromFloatDigits $ abs d
+        scString    = Scientific.formatScientific Scientific.Fixed Nothing sc
+    case Split.splitOn "." scString of
+        [int, frac] -> do
+            intPart <- Mutable.fromList $ map (fromIntegral . digitToInt) int
+            let minusLength = 1
+                dotLength   = 1
+            fracPart <- Mutable.fromList $ map (fromIntegral . digitToInt) frac
+            number   <- generalize <$> IR.number 10 intPart fracPart `withLength`
+                (length int + dotLength + length frac)
```
Comment (piotrMocz) [inline libs/luna-empire/src/Empire/ASTOps/Parse.hs]: I would extract `length int` and `length frac` into their own `let` bindings.
