### PR TITLE
Erroneous markers removal

### LINKED ISSUE #1087: Breaking line breaks the project
### General Summary

Breaking lines was never supported but now we are unable to revert broken state by using undo.

### Steps to Reproduce

1. Make some line in luna-studio and break it into two lines (I did it before `.`)
2. Graph is displaying some errors
3. Press ctrl-z

### Expected Result

- Change is reverted and graph is in state before 1.

### Actual Result

- Graph is still broken but in different way.

### Luna Version

- 1.41016

### PR DESCRIPTION
**Pull request by mikusp**
### Pull Request Description

After each substitute, we run `sanitizeMarkers` function on code, that attempts to remove markers that are incorrect, according to lexer output, or correct but their placement does not make sense in the context of code. Fixes #1087 and #448. 

If possible, please test before accepting. I've typed successfully TramsPlayground from scratch but I'd like to see more tests for this functionality.

### Checklist

- [x] The documentation has been updated if necessary.
- [x] The code conforms to the [Luna Style Guide](https://github.com/luna/wiki/blob/master/code-style/01.general.md) if it is Haskell.
- [x] The code has been tested where possible.

### CODE REVIEW

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 1]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+        dropMarker t =
+            let Just (markerStart, rest) = Text.uncons t
+            in if markerStart == '«'
+                then
+                    let numberDropped = Text.dropWhile isDigit rest
+                        Just (markerEnd, rest') = Text.uncons numberDropped
+                    in if markerEnd == '»'
+                        then rest'
+                        else after
+                else error $ "marker start is wrong: " <> [markerStart]
```
Comment (iamrecursion) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Should we be using `error` rather than something more structured?

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 2]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
         pure $ map (toRealDelta . toDelta) diffs
     substituteCode path changes
 
+-- | removeMarker removes marker at given position, assuming that marker
```
Comment (iamrecursion) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Would it potentially be better to employ the lexer itself to find the marker span? That way if we change what markers look like this code would still work?

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 3]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+--   consists of '«', non-zero number of digits, and '»'.
+removeMarker :: Text -> Int -> Text
+removeMarker code markerPos =
+    let (before, after) = Text.splitAt markerPos code
+        dropMarker t =
+            let Just (markerStart, rest) = Text.uncons t
+            in if markerStart == '«'
```
Comment (iamrecursion) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Same here, can use the token definition from [`Luna.Syntax.Text.Lexer.Grammar`](https://github.com/luna/luna/blob/master/syntax/text/lexer/src/Luna/Syntax/Text/Lexer/Grammar.hs#L331), given the lexer is imported anyway?

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 4]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+cumulativeOffsetStream :: [Lexer.Token a] -> [Lexer.Token a]
+cumulativeOffsetStream []     = []
+cumulativeOffsetStream tokens = tokens' where
+    tokens'    = scanl1 f tokens
+    f (Lexer.Token prevSpan accOffset _) (Lexer.Token span offset lexeme)
+        = Lexer.Token (span+offset) (accOffset + prevSpan) lexeme
+
+-- | Takes a pair of consecutive tokens and determines if a marker
+--   is placed in a proper position. If the second token is not a marker
+--   or if it seems to be correctly placed, Nothing is returned.
```
Comment (iamrecursion) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]:
```suggestion
--   or if it seems to be correctly placed, `Nothing` is returned.
```

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 5]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+--   If marker is determined to be incorrectly placed, Just offset
```
Comment (iamrecursion) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]:
```suggestion
--   If marker is determined to be incorrectly placed, `Just offset`
```

File: libs/luna-empire/test/Test/Code/MarkerSanitizerSpec.hs [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+            |]
+        expectedCode = normalizeLunaCode [r|
+            import Std.Base
+
+            «0»def main:
+                «1»node = foo . bar
+                None
+            |]
+        in sanitizeMarkers initialCode `shouldBe` expectedCode
+    it "removes three consecutive markers" $ let
```
Comment (iamrecursion) [inline libs/luna-empire/test/Test/Code/MarkerSanitizerSpec.hs]: Does it do this if the markers are separated by spaces?

File: libs/luna-empire/test/Test/Code/MarkerSanitizerSpec.hs [hunk 7]
```diff
@@ -0,0 +1,134 @@
...
+                «1»foo = 1
+                None
+            |]
+        in sanitizeMarkers initialCode `shouldBe` expectedCode
+    it "removes marker from accessor with spaces" $ let
+        initialCode = normalizeLunaCode [r|
+            import Std.Base
+
+            «0»def main:
+                «1»node = foo «2». bar
```
Comment (iamrecursion) [inline libs/luna-empire/test/Test/Code/MarkerSanitizerSpec.hs]: What about if the marker is the other side of the `.` operator?

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs (hunk 2 above)
Comment (mikusp) [reply libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Sometimes lexer does not report markers. `No<1>ne` will be lexed as Invalid InvalidSuffix and there's no Marker token to look for.

File: libs/luna-empire/test/Test/Code/MarkerSanitizerSpec.hs (hunk 6 above)
Comment (mikusp) [reply libs/luna-empire/test/Test/Code/MarkerSanitizerSpec.hs]: It should, I'll add test for that.

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs (hunk 2 above)
Comment (iamrecursion) [reply libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Makes sense!

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs (hunk 1 above)
Comment (mikusp) [reply libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: I think it's more like an assertion, if this case is hit, something deeply wrong happened and there's no point in trying to recover.

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 8]
```diff
@@ -1,22 +1,24 @@
...
+import qualified Empire.ASTOps.Parse                as ASTParse
+import qualified Empire.ASTOps.Read                 as ASTRead
+import qualified Empire.Commands.Code               as Code
+import qualified Empire.Commands.Publisher          as Publisher
+import qualified Empire.Data.Graph                  as Graph
+import qualified Empire.Data.Library                as Library
+import qualified Empire.Data.FileMetadata           as FileMetadata
+import qualified Empire.Empire                      as Empire
+import qualified LunaStudio.Data.GraphLocation      as GraphLocation
+import qualified Luna.Syntax.Text.Lexer             as Lexer
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: No need for extra spaces. Please revert

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 9]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
         pure $ map (toRealDelta . toDelta) diffs
     substituteCode path changes
 
+-- | removeMarker removes marker at given position, assuming that marker
+--   consists of '«', non-zero number of digits, and '»'.
+removeMarker :: Text -> Int -> Text
+removeMarker code markerPos =
+    let (before, after) = Text.splitAt markerPos code
+        dropMarker t =
+            let Just (markerStart, rest) = Text.uncons t
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Is this safe?

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 10]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+                        else after
+                else error $ "marker start is wrong: " <> [markerStart]
+    in Text.concat [before, dropMarker after]
+
+-- | This function computes offsets of each token from the beginning
+--   of the file and stores them in _offset field of Token
+cumulativeOffsetStream :: [Lexer.Token a] -> [Lexer.Token a]
+cumulativeOffsetStream []     = []
+cumulativeOffsetStream tokens = tokens' where
+    tokens'    = scanl1 f tokens
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Won't it work for empty list as well?

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 11]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+                        then rest'
+                        else after
+                else error $ "marker start is wrong: " <> [markerStart]
+    in Text.concat [before, dropMarker after]
+
+-- | This function computes offsets of each token from the beginning
+--   of the file and stores them in _offset field of Token
+cumulativeOffsetStream :: [Lexer.Token a] -> [Lexer.Token a]
+cumulativeOffsetStream []     = []
+cumulativeOffsetStream tokens = tokens' where
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: no reason for defining `token'`. Inline instead

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 12]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+--   by anything else than:
+--       - beginning of code
+--       - end of line
+--       - block start (:)
+isWrongMarker
+    :: (Lexer.Token Lexer.Symbol, Lexer.Token Lexer.Symbol)
+    -> Maybe Delta
+isWrongMarker tokens
+    | (Lexer.Token _ _ preceding,
+       Lexer.Token _ offset (Lexer.Marker _)) <- tokens =
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: can't we use lenses instead?

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 13]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+            Lexer.STX        -> Nothing
+            Lexer.EOL        -> Nothing
+            Lexer.BlockStart -> Nothing
+            _                -> Just offset
+    | otherwise = Nothing
+
+sanitizeMarkers :: Text -> Text
+sanitizeMarkers text = if null erroneousMarkers
+    then text
+    else removeErroneousMarkers (coerce erroneousMarkers) text where
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: `let ... in ...` pattern would be more readable

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 14]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+        removeErroneousMarkers markers code
+            = foldl' removeMarker code (reverse $ sort markers)
+        lexerStream      = Lexer.evalDefLexer (convert text)
+        cumulativeStream = cumulativeOffsetStream lexerStream
+        markersIndices   = findIndices (== '«') $ toList text
+        tokensForMarkers = map (\a -> (a, findToken cumulativeStream a))
+            $ coerce markersIndices
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]:
```
tokensForMarkers = (id &&& findToken cumulativeStream) <$> coerce markersIndices
```

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 15]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+        findToken stream index = find (\t -> t ^. Lexer.offset == index) stream
+        erroneousMarkers =
+            [ a | (a, Nothing) <- tokensForMarkers] <> wrongMarkers
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: <3

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 16]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+        precedingTokens  = zip cumulativeStream (tail cumulativeStream)
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: `$`

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 17]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+        wrongMarkers     = catMaybes $ map isWrongMarker precedingTokens
```
Comment (ljkania) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: wrongMarkers     = catMaybes $ isWrongMarker <$> precedingTokens

File: libs/luna-empire/test/Test/Code/MarkerSanitizerSpec.hs [hunk 18]
```diff
@@ -0,0 +1,134 @@
+module Test.Code.MarkerSanitizerSpec (spec) where
+
+import Empire.Prelude
+
+import Empire.Commands.Graph.Code     (sanitizeMarkers)
+import Test.Hspec                     (Spec, describe, it, parallel, shouldBe)
+import Test.Hspec.Empire              (normalizeLunaCode)
+import Text.RawString.QQ              (r)
```
Comment (ljkania) [inline libs/luna-empire/test/Test/Code/MarkerSanitizerSpec.hs]: Extra spaces

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs (hunk 9 above)
Comment (pmlodawski) [reply libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Even if it is safe now:
- it generates warning, so it have to be fixed
- safeness can be changed in the future when somebody will change something in this code and forgot about this unsafe pattern match
- there is no proof of safeness in the scope, or even a comment

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs (hunk 3 above)
Comment (pmlodawski) [reply libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: magic constant

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 19]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+removeMarker :: Text -> Int -> Text
+removeMarker code markerPos =
+    let (before, after) = Text.splitAt markerPos code
+        dropMarker t =
+            let Just (markerStart, rest) = Text.uncons t
+            in if markerStart == '«'
+                then
+                    let numberDropped = Text.dropWhile isDigit rest
+                        Just (markerEnd, rest') = Text.uncons numberDropped
+                    in if markerEnd == '»'
```
Comment (pmlodawski) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: magic constant

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 20]
```diff
@@ -57,10 +58,79 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
...
+            _                -> Just offset
+    | otherwise = Nothing
+
+sanitizeMarkers :: Text -> Text
+sanitizeMarkers text = let
+    removeErroneousMarkers markers code
+        = foldl' removeMarker code (reverse $ sort markers)
+    lexerStream      = Lexer.evalDefLexer (convert text)
+    cumulativeStream = cumulativeOffsetStream lexerStream
+    markersIndices   = findIndices (== '«') $ toList text
```
Comment (pmlodawski) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: magic constant
