### PR TITLE
Make sure Atom diffs are minimal and do not overwrite contexts

### LINKED ISSUE #1323: Editor deletes part of text being written on 'breadcrumb' error
### General Summary

When writing code in the editor, I think it tries to suggest variable names or something, but fails to do so and throws lots of errors.
Afterwards, parts of the text I was writing get deleted, so that I cannot really write code.

### Steps to Reproduce

1. Create a new project
2. Paste this code (other may work, but that's exactly what I've been working on)
```
import Std.Time
import Std.Base

class Looper a:
    Done a
    Next a (Looper a)

    def isStream: True

    def get: case self of
        Done a: a
        Next _ l: l.get

    def each f: case self of
        Done a: f a
        Next a l:
            f a
            l.each f

def unfoldLoop times initial f:
    case times of
        0: Done initial
        i:
            nxt = f initial
            Next initial (unfoldLoop times.pred nxt f)

def main:
    unfoldLoop1 = unfoldLoop 500 0 (i: seq (sleep 150.miliseconds.toMicroseconds) (i + 1))
    None
```
3. Try *manually* modifying main to
```
def main:
    unfoldLoop1 = unfoldLoop 500 0 (i: seq (sleep 150.miliseconds.toMicroseconds) (i + 1))
    unfoldLoop2 = unfoldLoop1.each (i: i * 100)
    None
```

### Expected Result

The code is modified.

### Actual Result

I get multiple red errors in the corner, and words/letters that I've written get randomly removed, so that I all managed to write was
```
def main:
    unfoldLoop1 = unfoldLoop 500 0 (i: seq (sleep 150.miliseconds.toMicroseconds) (i + 1))
    unfoldLoop
   None
```

The error I was getting (multiple times) has following log:
```
Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}

while processing event

empire.atom.file.substitute.response

======= logs: =======

=== luna-empire-stdout---supervisor-U8fNCW.log ===
INFO 2019-01-12T13:13:44.174558596Z	:: received empire.graph.program.request
INFO empire.graph.program.request: Request {_location = GraphLocation {_filePath = "/home/radeusgd/luna/projects/LunaLooper/src/Main.luna", _breadcrumb = Breadcrumb {_items = []}}, _prevLocationSettings = Nothing, _retrieveLocation = True}
INFO 2019-01-12T13:13:44.242813907Z	:: sending response for empire.graph.program.request
INFO 2019-01-12T13:13:44.242813907Z	:: Result {_currentLocation = GraphLocation {_filePath = "/home/radeusgd/luna/projects/LunaLooper/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}}, _diff = Diff {_reversedModifications = [SetGraph (ModificationSetGraph {_newGraph = Graph {_nodes = [ExpressionNode {_exprNodeId = 44766bf4-0b6b-427a-8f2d-f0aeb2cbc7fc, _expression = "unfoldLoop1 = unfoldLoop 500 0 \9403 None", _isDefinition = False, _name = Nothing, _code = "unfoldLoop1 = unfoldLoop 500 0 (i: seq (sleep 150.miliseconds.toMicroseconds) (i + 1))\n    \n     None", _inPorts = LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = [LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Arg 0], _name = "arg0", _valueType = TStar, _state = WithDefault (Expression "None")}}]}, _value = Port {_portId = [], _name = "alias", _valueType = TStar, _state = NotConnected}}, _outPorts = LabeledTree {_subtrees = OutPorts [], _value = Port {_portId = [], _name = "output", _valueType = TStar, _state = NotConnected}}, _nodeMeta = NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = 0.0, _vector2_y = 0.0}}, _displayResult = False, _selectedVisualizer = Nothing}, _canEnter = False}], _connections = [Connection {_src = OutPortRef {_srcNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 44766bf4-0b6b-427a-8f2d-f0aeb2cbc7fc}, _srcPortId = []}, _dst = InPortRef {_dstNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 000e868d-9d14-4853-a057-302f877c9c41}, _dstPortId = []}}], _inputSidebar = Just (InputSidebar {_inputNodeId = baad6ba1-c360-4e00-9457-b072f50e91f4, _inputEdgePorts = [], _isDef = True}), _outputSidebar = Just (OutputSidebar {_outputNodeId = 000e868d-9d14-4853-a057-302f877c9c41, _outputEdgePorts = LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "output", _valueType = TStar, _state = Connected}}}), _monads = [MonadPath {_monadType = TCons "IO" [], _path = []}], _imports = fromList ["Native","Std.Base","Std.Time"]}}),SetCode (ModificationSetCode {_newCode = Code "import Std.Time\nimport Std.Base\n\nclass Looper a:\n    Done a\n    Next a (Looper a)\n\n    def isStream: True\n\n    def get: case self of\n        Done a: a\n        Next _ l: l.get\n\n    def each f: case self of\n        Done a: f a\n        Next a l:\n            f a\n            l.each f\n\ndef unfoldLoop times initial f:\n    case times of\n        0: Done initial\n        i:\n            nxt = f initial\n            Next initial (unfoldLoop times.pred nxt f)\n\ndef main:\n    unfoldLoop1 = unfoldLoop 500 0 (i: seq (sleep 150.miliseconds.toMicroseconds) (i + 1))\n    \n     None\n"}),SetExternalVisPath (ModificationSetExternalVisPath {_newExternalVisPath = ExternalVisualizers {_projectVisualizers = Just "/home/radeusgd/luna/projects/LunaLooper/visualizers", _librariesVisualizers = fromList [("Dataframes","/tmp/.mount_luna-sNKvyEC/usr/config/env/Dataframes/visualizers"),("Std","/tmp/.mount_luna-sNKvyEC/usr/config/env/Std/visualizers")]}}),SetCamera (ModificationSetCamera {_newCameraTransformation = CameraTransformation {_screenToLogical = ┌                 ┐
│ 1.0 0.0 0.0 0.0 │
│ 0.0 1.0 0.0 0.0 │
│ 0.0 0.0 1.0 0.0 │
│ 0.0 0.0 0.0 1.0 │
└                 ┘, _logicalToScreen = ┌                 ┐
│ 1.0 0.0 0.0 0.0 │
│ 0.0 1.0 0.0 0.0 │
│ 0.0 0.0 1.0 0.0 │
│ 0.0 0.0 0.0 1.0 │
└                 ┘, _lastInverse = 0}}),SetDefaultVisualizers (ModificationSetDefaultVisualizers {_newDefaultVisualizers = fromList []}),SetBreadcrumb (ModificationSetBreadcrumb {_newBreadcrumb = Breadcrumb {_items = [Named {_name = "main", _breadcrumb = Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}}]}})]}}
INFO 2019-01-12T13:13:44.256112151Z	:: received empire.graph.program.response
INFO 2019-01-12T13:13:44.345393489Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:44.352005228Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:44.352151959Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:44.352282475Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:44.714606974Z	:: received empire.graph.nodesearch.request
INFO 2019-01-12T13:13:44.849731998Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:44.850070904Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:44.85031176Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:44.858455023Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:48.118488634Z	:: received empire.graph.saveSettings.request
INFO empire.graph.saveSettings.request: Request {_location = GraphLocation {_filePath = "/home/radeusgd/luna/projects/LunaLooper/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}}, _settings = LocationSettings {_visMap = Just (fromList []), _camera = CameraTransformation {_screenToLogical = ┌                 ┐
│ 1.0 0.0 0.0 0.0 │
│ 0.0 1.0 0.0 0.0 │
│ 0.0 0.0 1.0 0.0 │
│ 0.0 0.0 0.0 1.0 │
└                 ┘, _logicalToScreen = ┌                 ┐
│ 1.0 0.0 0.0 0.0 │
│ 0.0 1.0 0.0 0.0 │
│ 0.0 0.0 1.0 0.0 │
│ 0.0 0.0 0.0 1.0 │
└                 ┘, _lastInverse = 0}}}
INFO 2019-01-12T13:13:48.126132233Z	:: sending response for empire.graph.saveSettings.request
INFO 2019-01-12T13:13:48.126132233Z	:: ()
INFO 2019-01-12T13:13:48.126890188Z	:: received empire.graph.saveSettings.response
INFO 2019-01-12T13:13:50.569967627Z	:: received empire.atom.file.substitute.request
INFO empire.atom.file.substitute.request: Request {_location = GraphLocation {_filePath = "/home/radeusgd/luna/projects/LunaLooper/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}}, _diffs = [TextDiff {_range = Just (Point {_column = 4, _row = 29},Point {_column = 5, _row = 29}), _newText = "", _cursor = Just (Point {_column = 4, _row = 28})}]}
INFO 2019-01-12T13:13:50.650546074Z	:: sending response for empire.atom.file.substitute.request
INFO 2019-01-12T13:13:50.650546074Z	:: Diff {_reversedModifications = [RemoveConnection (ModificationRemoveConnection {_removeConnectionId = InPortRef {_dstNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 000e868d-9d14-4853-a057-302f877c9c41}, _dstPortId = []}}),SetOutputSidebar (ModificationSetOutputSidebar {_newOutputSidebar = Just (OutputSidebar {_outputNodeId = 000e868d-9d14-4853-a057-302f877c9c41, _outputEdgePorts = LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "output", _valueType = TStar, _state = WithDefault (Expression "None")}}})}),SetExpression (ModificationSetExpression {_setExpressionNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 44766bf4-0b6b-427a-8f2d-f0aeb2cbc7fc}, _newExpression = "unfoldLoop 500 0 \9403"}),RenameNode (ModificationRenameNode {_renameNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 44766bf4-0b6b-427a-8f2d-f0aeb2cbc7fc}, _newName = Just "unfoldLoop1"}),SetNodeCode (ModificationSetNodeCode {_setNodeCodeNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 44766bf4-0b6b-427a-8f2d-f0aeb2cbc7fc}, _newNodeCode = "unfoldLoop 500 0 (i: seq (sleep 150.miliseconds.toMicroseconds) (i + 1))"}),SetInPorts (ModificationSetInPorts {_setInPortsNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 44766bf4-0b6b-427a-8f2d-f0aeb2cbc7fc}, _newInPortTree = LabeledTree {_subtrees = InPorts {_self = Just (LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Self], _name = "self", _valueType = TStar, _state = NotConnected}}), _head = Nothing, _args = [LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Arg 0], _name = "arg0", _valueType = TStar, _state = WithDefault (Constant (IntValue 500))}},LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Arg 1], _name = "arg1", _valueType = TStar, _state = WithDefault (Constant (IntValue 0))}},LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Arg 2], _name = "arg2", _valueType = TStar, _state = WithDefault (Expression "(i: \171\&4\187seq (sleep (150 . miliseconds . toMicroseconds)) (i + 1))")}}]}, _value = Port {_portId = [], _name = "alias", _valueType = TStar, _state = WithDefault (Expression "unfoldLoop 500 0 (i: \171\&4\187seq (sleep (150 . miliseconds . toMicroseconds)) (i + 1))")}}}),SetOutPorts (ModificationSetOutPorts {_setOutPortsNodeLoc = NodeLoc {_path = NodePath {_localBc = Breadcrumb {_items = []}}, _nodeId = 44766bf4-0b6b-427a-8f2d-f0aeb2cbc7fc}, _newOutPortTree = LabeledTree {_subtrees = OutPorts [], _value = Port {_portId = [], _name = "unfoldLoop1", _valueType = TStar, _state = NotConnected}}})]}
INFO 2019-01-12T13:13:50.667475091Z	:: received empire.atom.file.substitute.update
INFO 2019-01-12T13:13:50.668844661Z	:: received empire.atom.file.substitute.response
INFO 2019-01-12T13:13:50.678125721Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:50.683211725Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:50.683566687Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:50.85468769Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:50.895690065Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:51.050070724Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:51.200293804Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:51.262861227Z	:: received empire.graph.node.updateMeta.update
INFO 2019-01-12T13:13:51.352989745Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:51.503439714Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:51.657606494Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:51.807988571Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:51.959150289Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:52.108633471Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:52.25900892Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:52.409433466Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:52.568266832Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:52.718573792Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:52.868951954Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.019223761Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.169549501Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.212042446Z	:: received empire.atom.file.substitute.request
INFO empire.atom.file.substitute.request: Request {_location = GraphLocation {_filePath = "/home/radeusgd/luna/projects/LunaLooper/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}}, _diffs = [TextDiff {_range = Just (Point {_column = 4, _row = 28},Point {_column = 4, _row = 28}), _newText = "unf", _cursor = Just (Point {_column = 7, _row = 28})}]}
INFO 2019-01-12T13:13:53.29262795Z	:: sending response for empire.atom.file.substitute.request
INFO 2019-01-12T13:13:53.29262795Z	:: Diff {_reversedModifications = [AddNode (ModificationAddNode {_newNode = ExpressionNode {_exprNodeId = 56e3dccb-b5fb-43e9-bff7-e6520f07f985, _expression = "\8226", _isDefinition = False, _name = Nothing, _code = "unf", _inPorts = LabeledTree {_subtrees = InPorts {_self = Just (LabeledTree {_subtrees = InPorts {_self = Nothing, _head = Nothing, _args = []}, _value = Port {_portId = [Self], _name = "self", _valueType = TStar, _state = NotConnected}}), _head = Nothing, _args = []}, _value = Port {_portId = [], _name = "alias", _valueType = TStar, _state = NotConnected}}, _outPorts = LabeledTree {_subtrees = OutPorts [], _value = Port {_portId = [], _name = "output", _valueType = TStar, _state = NotConnected}}, _nodeMeta = NodeMeta {_position = Position {fromPosition = Vector2 {_vector2_x = 320.0, _vector2_y = 0.0}}, _displayResult = False, _selectedVisualizer = Nothing}, _canEnter = False}})]}
INFO 2019-01-12T13:13:53.330402617Z	:: received empire.atom.file.substitute.update
INFO 2019-01-12T13:13:53.330690256Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.33091713Z	:: received empire.atom.file.substitute.response
INFO 2019-01-12T13:13:53.340541865Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:53.340898565Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:53.341454736Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:53.345478877Z	:: received empire.graph.node.typecheck
INFO 2019-01-12T13:13:53.345697658Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.491832983Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.501196724Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.643253404Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.79269304Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:53.951419206Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:54.05928652Z	:: received empire.atom.file.substitute.request
INFO empire.atom.file.substitute.request: Request {_location = GraphLocation {_filePath = "/home/radeusgd/luna/projects/LunaLooper/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}}, _diffs = [TextDiff {_range = Just (Point {_column = 0, _row = 0},Point {_column = 0, _row = 30}), _newText = "import Std.Time\nimport Std.Base\n\nclass Looper a:\n    Done a\n    Next a (Looper a)\n\n    def isStream: True\n\n    def get: case self of\n        Done a: a\n        Next _ l: l.get\n\n    def each f: case self of\n        Done a: f a\n        Next a l:\n            f a\n            l.each f\n\ndef unfoldLoop times initial f:\n    case times of\n        0: Done initial\n        i:\n            nxt = f initial\n            Next initial (unfoldLoop times.pred nxt f)\n\ndef main:\n    unfoldLoop1 = unfoldLoop 500 0 (i: seq (sleep 150.miliseconds.toMicroseconds) (i + 1))\n    unfld\n    None\n", _cursor = Just (Point {_column = 9, _row = 28})}]}
ERROR 2019-01-12T13:13:54.110824399Z	:: error during processing request empire.atom.file.substitute.request: Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}
INFO 2019-01-12T13:13:54.11979615Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:54.120099649Z	:: received empire.atom.file.substitute.update
INFO 2019-01-12T13:13:54.12190565Z	:: received empire.atom.file.substitute.response
INFO 2019-01-12T13:13:54.258145477Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:54.408340507Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:54.558922159Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:54.730069565Z	:: received empire.graph.result.update
INFO 2019-01-12T13:13:54.760824124Z	:: received empire.atom.file.substitute.request
INFO empire.atom.file.substitute.request: Request {_location = GraphLocation {_filePath = "/home/radeusgd/luna/projects/LunaLooper/src/Main.luna", _breadcrumb = Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}}, _diffs = [TextDiff {_range = Just (Point {_column = 0, _row = 0},Point {_column = 0, _row = 30}), _newText = "import Std.Time\nimport Std.Base\n\nclass Looper a:\n    Done a\n    Next a (Looper a)\n\n    def isStream: True\n\n    def get: case self of\n        Done a: a\n        Next _ l: l.get\n\n    def each f: case self of\n        Done a: f a\n        Next a l:\n            f a\n            l.each f\n\ndef unfoldLoop times initial f:\n    case times of\n        0: Done initial\n        i:\n            nxt = f initial\n            Next initial (unfoldLoop times.pred nxt f)\n\ndef main:\n    unfoldLoop1 = unfoldLoop 500 0 (i: seq (sleep 150.miliseconds.toMicroseconds) (i + 1))\n    unfldoo\n    None\n", _cursor = Just (Point {_column = 11, _row = 28})}]}
ERROR 2019-01-12T13:13:54.793292895Z	:: error during processing request empire.atom.file.substitute.request: Breadcrumb {_items = [Definition {_nodeId = f22a1b23-2289-4363-b641-811422d07348}]}
INFO 2019-01-12T13:13:54.794305893Z	:: received empire.atom.file.substitute.update
INFO 2019-01-12T13:13:54.811266038Z	:: received empire.atom.file.substitute.response
INFO 2019-01-12T13:13:54.86074984Z	:: received empire.graph.result.update
```

### Luna Version
"1.6.1.16" (I wanted to check it at 1.6.1.17 which is current latest version, but the lunaInstaller wasn't able to download it)

### PR DESCRIPTION
**Pull request by kustosz**
### Pull Request Description

This fixes #1323. The issue arising was a strange one and in its core is a wrong Atom behavior.
For whatever reason, sometimes when typing, Atom decides to send the whole file as changed instead of just selecting the relevant part. Due to Atom not knowing about markers, it was sending a diff for "whole file" range, containing the whole file, but without markers. This in turn removed the markers from existing code, making the current context (identified by marker) non existent. The new architecture of events made the whole thing a bit more context-sensitive, resulting in a behavior of randomly throwing user to the file toplevel and typechecker failing with a nasty exception. The solution proposed in this PR is to check how long the real diff is and applying the minimal suffix. This makes sure we won't randomly get thrown out of the context unless it really is broken.

### Checklist

- [x] The documentation has been updated if necessary.
- [x] The code conforms to the [Luna Style Guide](https://github.com/luna/wiki/blob/master/code-style/01.general.md) if it is Haskell.
- [x] The code has been tested where possible.

### CODE REVIEW

File: libs/luna-empire/src/Empire/Commands/Graph/Code.hs [hunk 1]
```diff
@@ -54,9 +54,19 @@ substituteCodeFromPoints path (breakDiffs -> diffs) = do
                 Just (char, _) -> if isSpace char
                     then Code.viewDeltasToRealBeforeMarker
                     else Code.viewDeltasToReal
+            minimizeDiff (beg, end, newCode) = (newBeg, end, minimalCode) where
```
Comment (wdanilo) [inline libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Could you please provide a detailed comment in the code why this step is needed? Otherwise it is just some kind of fix which nobody will be aware of in couple of weeks.

Comment (wdanilo) [reply libs/luna-empire/src/Empire/Commands/Graph/Code.hs]: Plus, why don't we extract such helper function to top-level? Imo keeping such utility functions in let, without proper typing their signatures makes them really hard to follow. Keeping them in top level with proper signatures would allow the reader to understand them faster and while reading the body of `substituteCodeFromPoints` it will help to focus on what really the code does – now its body is cluttered with helper, untyped functions. The same applies to other helper functions there.
